version: "3"

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    env_file:
#      - ./.env.dev
#  db:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#      -